name: mototracker
description: Track your ride

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^4.0.0
  equatable: ^1.1.1
  background_locator: 1.1.2+2
  location_permissions: ^2.0.5
  path_provider: ^1.6.9
  meta: ^1.1.8
  moor_ffi: ^0.5.0
  moor: ^3.1.0
  path: ^1.7.0
  provider: ^4.1.2
  flutter_slidable: ^0.5.4
  json_serializable: ^3.3.0
  flutter_map: ^0.9.0
  latlong: ^0.6.1
  shared_preferences: ^0.5.7+3
  flutter_svg: ^0.17.4

  cupertino_icons: ^0.1.3

dev_dependencies:
  moor_generator: ^3.1.0
  build_runner: ^1.10.0
  flutter_launcher_icons: ^0.7.5


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true

  assets:
     - assets/
  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf

